import pygame

# screen
WIDTH, HEIGHT = 500, 550

# grid
CELL_SIZE = 50
GAP = 5
MARGIN = 12
GRID_ROWS, GRID_COLS = 3, 5
GRID_POS = (WIDTH - (CELL_SIZE * GRID_COLS + GAP * (GRID_COLS - 1))) / 2

# enemy
ENEMY_SIZE = 40